version: '3.8'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/frontend/app
      - /frontend/app/node_modules
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BACKEND_URL: http://backend:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/backend/app
      - /backend/app/node_modules
    environment:
      NODE_ENV: production
